DEFAULT_AI_SETTINGS = {
    "project_price_ranges": [
        {"key": "landing_page", "label": "لندینگ پیج", "price_range": "۸ تا ۱۸ میلیون تومان", "timeline": "۵ تا ۱۰ روز"},
        {"key": "corporate_cms", "label": "سایت شرکتی/CMS", "price_range": "۱۸ تا ۴۵ میلیون تومان", "timeline": "۲ تا ۴ هفته"},
        {"key": "woocommerce_store", "label": "فروشگاه WooCommerce/Shopify", "price_range": "۳۵ تا ۹۰ میلیون تومان", "timeline": "۳ تا ۶ هفته"},
        {"key": "custom_ecommerce", "label": "فروشگاه کاملاً اختصاصی", "price_range": "۲۵۰ تا ۹۰۰+ میلیون تومان", "timeline": "۲ تا ۶ ماه"},
        {"key": "admin_dashboard", "label": "داشبورد/پنل اختصاصی", "price_range": "۹۰+ میلیون تومان", "timeline": "۶ هفته به بالا"},
        {"key": "payment_gateway", "label": "اتصال درگاه پرداخت", "price_range": "۱۰ تا ۴۵ میلیون تومان", "timeline": "۳ تا ۱۰ روز"},
        {"key": "seo_cms", "label": "SEO/بلاگ/CMS", "price_range": "۱۵ تا ۷۵ میلیون تومان", "timeline": "۱ تا ۴ هفته"},
    ],
    "budget_plan_thresholds": [
        {"key": "economic", "label": "Economic", "display": "اقتصادی", "max_million_toman": 30},
        {"key": "professional", "label": "Professional", "display": "حرفه‌ای", "min_million_toman": 30, "max_million_toman": 80},
        {"key": "fully_custom", "label": "Fully Custom", "display": "کاملاً اختصاصی", "min_million_toman": 80},
    ],
    "currency_label": "میلیون تومان",
    "timeline_estimates": [
        {"project_type": "landing_page", "estimate": "۵ تا ۱۰ روز"},
        {"project_type": "cms_website", "estimate": "۲ تا ۴ هفته"},
        {"project_type": "store_cms", "estimate": "۳ تا ۶ هفته"},
        {"project_type": "custom_platform", "estimate": "۲ تا ۶ ماه"},
    ],
    "ai_sales_rules": [
        "اگر بودجه پایین است، CMS، WordPress، WooCommerce، Shopify یا no-code/low-code پیشنهاد بده.",
        "اگر مشتری فروشگاه کاملاً اختصاصی با بودجه کم می‌خواهد، محترمانه توضیح بده بودجه برای توسعه کاملاً اختصاصی مناسب نیست.",
        "اگر SEO مهم است، WordPress، CMS یا headless CMS را به عنوان گزینه مناسب بررسی کن.",
        "اگر scalability، SaaS، داشبورد اختصاصی یا رشد بلندمدت مهم است، Next.js، React، Django، Node.js یا بک‌اند اختصاصی پیشنهاد بده.",
        "اگر پروژه از بودجه بزرگ‌تر است، MVP، توسعه فازبندی‌شده یا نسخه ساده‌تر برای لانچ پیشنهاد بده.",
        "قیمت نهایی قطعی نده؛ فقط بازه تقریبی بده و بگو بعد از بررسی جزئیات نهایی می‌شود.",
        "در هر پیام حداکثر دو سوال بپرس و از سوال‌پیچ کردن مشتری پرهیز کن.",
    ],
    "recommended_technologies": [
        {"condition": "بودجه اقتصادی یا نیاز ساده", "recommendation": "WordPress, WooCommerce, Shopify, Webflow یا CMS آماده"},
        {"condition": "SEO و محتوا مهم است", "recommendation": "WordPress, Headless CMS, Next.js برای صفحات سریع"},
        {"condition": "داشبورد، SaaS، مقیاس‌پذیری یا منطق اختصاصی مهم است", "recommendation": "Next.js/React + FastAPI/Django/Node.js + PostgreSQL"},
        {"condition": "MVP سریع لازم است", "recommendation": "فاز اول ساده با CMS/low-code یا بک‌اند سبک"},
    ],
    "chatbot_question_flow": [
        "نوع پروژه و هدف اصلی چیست؟",
        "امکانات ضروری که بدون آن پروژه ناقص است چیست؟",
        "بودجه یا سطح مدنظر شما چیست: اقتصادی، حرفه‌ای یا کاملاً اختصاصی؟",
        "زمان‌بندی تقریبی مدنظر شما چیست؟",
    ],
    "predefined_response_templates": {
        "low_budget_custom": "برای توسعه کاملاً اختصاصی، این بودجه احتمالاً کافی نیست. پیشنهاد بهتر این است که نسخه اول را با CMS یا MVP سبک شروع کنیم و امکانات اختصاصی را فازبندی کنیم.",
        "mvp_suggestion": "برای شروع سریع‌تر و کاهش ریسک، پیشنهاد می‌کنم نسخه MVP را با امکانات ضروری لانچ کنیم و قابلیت‌های پیشرفته را در فاز بعد اضافه کنیم.",
        "fit_budget": "با اطلاعات فعلی، بودجه و سطح انتظار پروژه قابل مذاکره و منطقی به نظر می‌رسد؛ برای قیمت دقیق‌تر نیاز به بررسی جزئیات داریم.",
    },
    "lead_scoring_rules": [
        {"condition": "بودجه مناسب و زمان‌بندی منطقی", "score": 30},
        {"condition": "نیاز مشخص و امکانات واضح", "score": 25},
        {"condition": "بودجه پایین برای پروژه اختصاصی", "score": -25},
        {"condition": "زمان‌بندی غیرواقعی", "score": -20},
        {"condition": "تصمیم‌گیرنده جدی یا آماده پرداخت", "score": 20},
    ],
    "payment_terms": {
        "default_deposit_percentage": 50,
        "minimum_deposit_percentage": 30,
        "notes": "درصد پیش‌پرداخت توسط ادمین قابل تغییر است و بعد از تایید نهایی سفارش به مشتری اعلام می‌شود.",
    },
}
